---
# Fetch dependencies (platform-specific)
- name: install dependencies
  ansible.builtin.apt: pkg={{ item }} update_cache=yes cache_valid_time=86400 state=present
  with_items:
    - gcc 
    - make
    - libc6-dev
    - libtool
    - autoconf
    - liburcu-dev
    - libgnutls28-dev
    - libjansson-dev
  when: ansible_os_family == "Debian" 
- name: dependencies (FreeBSD)
  community.general.pkgng: name={{ item }} state=present
  with_items:
    - security/nettle
    - security/gnutls
    - devel/jansson
    - sysutils/liburcu
    - databases/lmdb
  when: ansible_os_family == "FreeBSD"

# Clone and build from sources
- name: git clone
  ansible.builtin.git: repo=http://gitlab.labs.nic.cz/labs/knot.git dest=/usr/local/src/knot version={{ knot_git_branch }} update=yes
- name: configure
  ansible.builtin.shell: autoreconf -if && ./configure --prefix={{ knot_install_dir }} chdir=/usr/local/src/knot creates=/usr/local/src/knot/Makefile
- name: build
  # possible ambiguous replacement: command : ansible.builtin.command | community.ciscosmb.command | community.routeros.command
  ansible.builtin.command: make -j{{ansible_processor_count}} chdir=/usr/local/src/knot creates=/usr/local/src/knot/src/knotd
- name: install
  # possible ambiguous replacement: command : ansible.builtin.command | community.ciscosmb.command | community.routeros.command
  ansible.builtin.command: make install chdir=/usr/local/src/knot creates={{ knot_install_dir }}/sbin/knotd

# Post-installation
- name: add knot group
  # possible ambiguous replacement: group : ansible.builtin.group | awx.awx.group | microsoft.ad.group
  ansible.builtin.group:
    name={{ knot_group }}
    comment="Knot DNS"
- name: add knot user
  # possible ambiguous replacement: user : ansible.builtin.user | awx.awx.user | cisco.dnac.user | inspur.ispim.user | inspur.sm.user | lowlydba.sqlserver.user | microsoft.ad.user | sensu.sensu_go.user | theforeman.foreman.user | vultr.cloud.user
  ansible.builtin.user:
    name={{ knot_user }}
    comment="Knot DNS"
    home={{ knot_install_dir }}
    shell=/bin/false
    groups={{knot_group}}
    system=yes

- name: make sure directories are writeable
  ansible.builtin.file: path={{ item }}  state=directory owner={{ knot_user }}
  with_items:
    - "{{ knot_install_dir }}/etc/knot"
    - "{{ knot_install_dir }}/var/lib/knot"
    - "{{ knot_install_dir }}/var/run/lib/knot"